'use client';
import Link from 'next/link';
import { Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { usePlatform } from '@/lib/hooks';
import { platform } from '@/lib/platform-client';
import { api } from '@/lib/api';
import { DeviceIcon, Modal } from '@/components/primitives';
import type { Device } from '@/shared/protocol';
export default function DevicesPage() {
  const state = usePlatform(); const [remove, setRemove] = useState<Device | null>(null);
  async function trust(device: Device) { try { await api(`/devices/${device.id}/trust`, { trusted: !device.trusted }); } catch (error) { platform.error(error); } }
  return <><div className="page-heading"><div><span className="eyebrow">FAMILIAR FACES. DIFFERENT SCREENS.</span><h1>Your devices.</h1><p>Make yourself at home, wherever you’re sending from.</p></div><Link href="/connect" className="button primary small"><Plus size={16}/> Connect a device</Link></div><div className="managed-devices">{[...(state.device ? [state.device] : []), ...state.devices].map(d => <article className="managed-device surface" key={d.id}><span className="device-illustration"><DeviceIcon type={d.type} size={35}/></span><div className="managed-device-info"><h2>{d.name}</h2><p>{d.id === state.device?.id ? 'This device' : d.trusted ? 'Trusted device' : 'Paired device'} <i/> <span className="device-status"><i className={`status-dot ${d.online ? '' : 'muted'}`}/>{d.online ? 'Online' : `Last seen ${new Date(d.lastSeen).toLocaleDateString()}`}</span></p></div>{d.id === state.device?.id ? <Link className="text-button" href="/settings">Rename</Link> : <div className="device-controls">{state.device?.userId && state.device.userId === d.userId && <button className="button secondary-button small" onClick={() => void trust(d)}><ShieldCheck size={15}/>{d.trusted ? 'Revoke trust' : 'Trust device'}</button>}<button className="icon-button" aria-label={`Remove ${d.name}`} onClick={() => setRemove(d)}><Trash2 size={17}/></button></div>}</article>)}</div>{!state.devices.length && <div className="large-empty"><span className="feature-icon"><Plus size={28}/></span><h2>Good things come in pairs.</h2><p>Connect another device to start sending.</p><Link href="/connect" className="button primary">Connect a device</Link></div>}<div className="info-banner"><ShieldCheck size={20}/><p>Trust is available when both devices are signed in to the same account. Every incoming transfer still asks for your approval.</p></div>{remove && <Modal title={`Disconnect ${remove.name}?`} onClose={() => setRemove(null)}><p className="modal-description">You can reconnect anytime with a new pairing code. Trust will also be removed.</p><div className="modal-actions"><button className="button secondary-button" onClick={() => setRemove(null)}>Keep connected</button><button className="button primary" onClick={() => { void api(`/devices/${remove.id}`, {}, 'DELETE').then(() => setRemove(null)).catch(e => platform.error(e)); }}>Disconnect</button></div></Modal>}</>;
}
