import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { Platform } from '../server/platform';
import { Store } from '../server/store';
import { hash } from '../server/security';
import { generateIdentity } from '../src/transfer/crypto';
test('authenticated pairing, expiration, confirmation, transfers and authorization', async () => {
  const store = new Store(); const platform = new Platform(store,'http://localhost');
  const server = createServer((req,res) => { void platform.handle(req,res); });
  await new Promise<void>(resolve => server.listen(0,'127.0.0.1',resolve));
  const address = server.address(); assert.ok(address && typeof address === 'object'); const base = `http://127.0.0.1:${address.port}/api/v1`;
  const request = async (path:string, token:string|null, body?:unknown, method?:string) => {
    const response = await fetch(base+path,{method:method || (body === undefined?'GET':'POST'),headers:{'x-neardrop-client':'native','Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});
    return {status:response.status,body:await response.json()};
  };
  try {
    const identity = await generateIdentity();
    const alice = await request('/devices/register',null,{name:'Alice',type:'laptop',publicKey:identity.publicKey});
    const bob = await request('/devices/register',null,{name:'Bob',type:'android',publicKey:(await generateIdentity()).publicKey});
    const mallory = await request('/devices/register',null,{name:'Mallory',type:'phone',publicKey:(await generateIdentity()).publicKey});
    assert.equal(alice.status,201); assert.ok(alice.body.token); assert.equal(alice.body.device.tokenHash,undefined);
    assert.equal((await request('/devices',null)).status,401);
    assert.equal((await request(`/devices/${bob.body.device.id}`,alice.body.token,{name:'Hacked'},'PATCH')).status,404);
    const code = await request('/pairing/create',alice.body.token,{}); assert.equal(code.status,200);
    assert.notEqual(store.pairings.get(code.body.id)?.codeHash,code.body.code);
    store.devices.get(alice.body.device.id)!.online = true; store.devices.get(bob.body.device.id)!.online = true;
    const joined = await request('/pairing/join',bob.body.token,{code:code.body.code}); assert.equal(joined.status,200);
    const payload = {receiverId:bob.body.device.id,item:{name:'hello.txt',size:12,mime:'text/plain',kind:'file'}};
    assert.equal((await request('/transfers',alice.body.token,payload)).status,403);
    assert.equal((await request('/pairing/confirm',mallory.body.token,{id:joined.body.id})).status,400);
    assert.equal((await request('/pairing/confirm',alice.body.token,{id:joined.body.id})).status,200);
    assert.equal((await request('/pairing/join',mallory.body.token,{code:code.body.code})).status,400);
    assert.equal((await request('/devices',alice.body.token)).body.devices.length,1);
    assert.equal((await request(`/devices/${bob.body.device.id}/trust`,alice.body.token,{trusted:true})).status,403);
    const transfer = await request('/transfers',alice.body.token,payload); assert.equal(transfer.status,201); const tid = transfer.body.transfer.id;
    assert.equal((await request(`/transfers/${tid}`,mallory.body.token)).status,404);
    assert.equal((await request(`/transfers/${tid}/accept`,alice.body.token,{})).status,403);
    await platform.message(store.devices.get(alice.body.device.id)!,JSON.stringify({type:'transfer.complete',transferId:tid})); assert.equal(store.transfers.get(tid)?.status,'waiting');
    assert.equal((await request(`/transfers/${tid}/accept`,bob.body.token,{})).status,200);
    await platform.message(store.devices.get(bob.body.device.id)!,JSON.stringify({type:'transfer.complete',transferId:tid})); assert.equal(store.transfers.get(tid)?.status,'preparing');
    assert.equal((await request(`/transfers/${tid}/cancel`,bob.body.token,{})).status,200);
    assert.equal((await request(`/transfers/${tid}/accept`,bob.body.token,{})).status,409);
    const expired = await request('/pairing/create',alice.body.token,{}); store.pairings.get(expired.body.id)!.expiresAt = Date.now()-1;
    assert.equal((await request('/pairing/join',mallory.body.token,{code:expired.body.code})).status,400);
    assert.equal((await request('/devices/register',null,{name:'X',type:'invalid'})).status,400);
    const csrf = await fetch(base+'/pairing/create',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json',Authorization:`Bearer ${alice.body.token}`},body:'{}'}); assert.equal(csrf.status,403);
    assert.equal((await request(`/devices/${bob.body.device.id}`,alice.body.token,{},'DELETE')).status,200);
    assert.equal(store.related(alice.body.device.id,bob.body.device.id),false);
  } finally { await new Promise<void>(resolve => server.close(() => resolve())); }
});
test('relay routing requires acceptance, exact sequence, receiver acknowledgement and complete size', async () => {
  const store = new Store(); const platform = new Platform(store,'http://localhost');
  const alice = {id:crypto.randomUUID(),name:'Alice',type:'laptop' as const,publicKey:(await generateIdentity()).publicKey,userId:null,online:true,lastSeen:new Date().toISOString(),tokenHash:hash('alice'),expiresAt:Date.now()+10000};
  const bob = {...alice,id:crypto.randomUUID(),name:'Bob',tokenHash:hash('bob')}; const other = {...alice,id:crypto.randomUUID(),name:'Other'};
  store.devices.set(alice.id,alice); store.devices.set(bob.id,bob); store.devices.set(other.id,other);
  await store.saveRelationship({a:alice.id,b:bob.id,trustedBy:[]});
  const id = crypto.randomUUID(); const now = new Date().toISOString();
  await store.saveTransfer({id,senderId:alice.id,receiverId:bob.id,senderName:'Alice',receiverName:'Bob',item:{name:'small.bin',size:5,mime:'',kind:'file'},status:'waiting',transport:null,bytes:0,createdAt:now,updatedAt:now});
  const send = (device:typeof alice,event:unknown) => platform.message(device,JSON.stringify(event));
  await send(alice,{type:'transfer.transport',transferId:id,transport:'relay'}); assert.equal(store.transfers.get(id)!.status,'waiting');
  store.transfers.get(id)!.status='preparing';
  await send(other,{type:'transfer.transport',transferId:id,transport:'relay'}); assert.equal(store.transfers.get(id)!.status,'preparing');
  await send(alice,{type:'transfer.transport',transferId:id,transport:'relay'}); assert.equal(store.transfers.get(id)!.status,'transferring');
  await send(alice,{type:'transfer.chunk',transferId:id,sequence:1,data:Buffer.alloc(21).toString('base64')}); assert.equal(platform.relaySequence.get(id)!.sent,-1);
  await send(alice,{type:'transfer.chunk',transferId:id,sequence:0,data:Buffer.alloc(22).toString('base64')}); assert.equal(platform.relaySequence.get(id)!.sent,-1);
  await send(alice,{type:'transfer.chunk',transferId:id,sequence:0,data:Buffer.alloc(21).toString('base64')}); assert.equal(platform.relaySequence.get(id)!.sent,0);
  await send(alice,{type:'transfer.ack',transferId:id,sequence:0,bytes:5}); assert.equal(store.transfers.get(id)!.bytes,0);
  await send(bob,{type:'transfer.complete',transferId:id}); assert.equal(store.transfers.get(id)!.status,'transferring');
  await send(bob,{type:'transfer.ack',transferId:id,sequence:0,bytes:6}); assert.equal(store.transfers.get(id)!.bytes,0);
  await send(bob,{type:'transfer.ack',transferId:id,sequence:0,bytes:5}); assert.equal(store.transfers.get(id)!.bytes,5);
  await send(alice,{type:'transfer.complete',transferId:id}); assert.equal(store.transfers.get(id)!.status,'transferring');
  await send(bob,{type:'transfer.complete',transferId:id}); assert.equal(store.transfers.get(id)!.status,'completed');
  await send(alice,{type:'transfer.fail',transferId:id,reason:'late'}); assert.equal(store.transfers.get(id)!.status,'completed');
});
