'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Bell, Check, LogOut, Moon, ShieldCheck } from 'lucide-react';
import { usePlatform } from '@/lib/hooks';
import { platform } from '@/lib/platform-client';
import { api } from '@/lib/api';
import { authClient } from '@/lib/auth';
import { preferences } from '@/lib/local-preferences';
export default function SettingsPage() {
  const state = usePlatform(); const [name, setName] = useState(''); const [theme, setTheme] = useState('light'); const [notifications, setNotifications] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { setName(state.device?.name || ''); }, [state.device?.name]);
  useEffect(() => { setTheme(document.documentElement.dataset.theme || 'light'); setNotifications(preferences.getItem('nd-notifications') === 'true'); }, []);
  async function toggleNotifications() {
    if (!('Notification' in window)) { platform.error('Notifications are unavailable here. Incoming transfers will still appear in NearDrop. On iPhone, try adding NearDrop to your Home Screen.'); return; }
    if (notifications) { setNotifications(false); preferences.setItem('nd-notifications', 'false'); return; }
    const permission = await Notification.requestPermission(); const enabled = permission === 'granted'; setNotifications(enabled); preferences.setItem('nd-notifications', String(enabled)); if (!enabled) platform.error('Notifications are blocked. You can enable them in your browser settings.');
  }
  async function signOut() { try { await api('/auth/sign-out', {}); await authClient()?.auth.signOut(); preferences.removeItem('nd-identity'); location.assign('/drop'); } catch (error) { platform.error(error); } }
  return <><div className="page-heading"><div><span className="eyebrow">MAKE YOURSELF AT HOME</span><h1>A few personal touches.</h1><p>Keep things simple. Make NearDrop yours.</p></div></div><div className="settings-stack"><section className="settings-section"><h2>General</h2><div className="surface settings-body"><form className="setting-row" onSubmit={e => { e.preventDefault(); void platform.rename(name).then(() => { setSaved(true); setTimeout(() => setSaved(false), 2000); }).catch(e => platform.error(e)); }}><div><label htmlFor="device-name">Device name</label><p>A familiar name makes your device easy to recognize.</p></div><div className="setting-input"><input id="device-name" value={name} onChange={e => setName(e.target.value)} maxLength={48} required/><button className="button primary small" disabled={!name.trim() || state.status !== 'online'}>{saved ? <><Check size={15}/> Saved</> : 'Save'}</button></div></form><div className="setting-row"><div><h3>Account</h3><p>{state.device?.userId ? 'This device is linked to your verified account.' : 'Guest mode is ready to use. Sign in for persistent device trust and history.'}</p></div>{state.device?.userId ? <button className="button secondary-button small" onClick={() => void signOut()}><LogOut size={15}/> Sign out</button> : <Link className="button secondary-button small" href="/auth/sign-in">Sign in</Link>}</div></div></section><section className="settings-section"><h2>Transfers & privacy</h2><div className="surface settings-body"><div className="setting-row"><div><h3>Ask before receiving</h3><p>You decide what arrives. Every transfer requires your approval.</p></div><span className="setting-fixed"><ShieldCheck size={16}/> Always on</span></div><div className="setting-row"><div><h3>Transfer notifications</h3><p>Get a heads-up when an item arrives, where your browser supports it.</p></div><button className={`switch ${notifications ? 'on' : ''}`} role="switch" aria-checked={notifications} aria-label="Transfer notifications" onClick={() => void toggleNotifications()}><span/></button></div><div className="setting-row"><div><h3>Transfer history</h3><p>Metadata is retained for up to 30 days. Your file contents are not stored on our server.</p></div><Link className="text-button" href="/history">Manage history</Link></div></div></section><section className="settings-section"><h2>Appearance</h2><div className="surface settings-body"><div className="setting-row"><div><label htmlFor="theme">Theme</label><p>A comfortable view, day or night.</p></div><select id="theme" value={theme} onChange={e => { setTheme(e.target.value); document.documentElement.dataset.theme = e.target.value; preferences.setItem('nd-theme', e.target.value); }}><option value="light">Light</option><option value="dark">Dark</option></select></div></div></section><p className="settings-footnote">NearDrop v1.0 <i/> <Link href="/privacy">Privacy & browser support</Link></p></div></>;
}
