'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useState, type ReactNode } from 'react';
import { ArrowUpRight, Check, CircleHelp, Clock3, Command, Laptop, MonitorSmartphone, Moon, Plus, Radio, Settings2, ShieldCheck, Sun, WifiOff, X } from 'lucide-react';
import { Brand } from './brand';
import { DeviceIcon, Modal } from './primitives';
import { PairingPanel } from './pairing';
import { usePlatform } from '@/lib/hooks';
import { platform } from '@/lib/platform-client';
import { preferences } from '@/lib/local-preferences';
import { MessageSquare } from 'lucide-react';
import { connectionHints, connectionLabels } from '@/lib/connection-status';
const navigation = [{ href: '/drop', label: 'Transfer', Icon: ArrowUpRight }, { href: '/chat', label: 'Chat', Icon: MessageSquare }, { href: '/devices', label: 'Devices', Icon: MonitorSmartphone }, { href: '/history', label: 'History', Icon: Clock3 }];
export function ThemeButton() {
  const [dark, setDark] = useState(false);
  useEffect(() => setDark(document.documentElement.dataset.theme === 'dark'), []);
  return <button className="icon-button" title={dark ? 'Switch to light theme' : 'Switch to dark theme'} aria-label={dark ? 'Switch to light theme' : 'Switch to dark theme'} onClick={() => { const next = !dark; setDark(next); document.documentElement.dataset.theme = next ? 'dark' : 'light'; preferences.setItem('nd-theme', next ? 'dark' : 'light'); }}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button>;
}
export function AppShell({ children }: { children: ReactNode }) {
  const path = usePathname(); const state = usePlatform(); const [pair, setPair] = useState(false); const [help, setHelp] = useState(false);
  useEffect(() => { if ('serviceWorker' in navigator) void navigator.serviceWorker.register('/sw.js').catch(() => undefined); }, []);
  useEffect(() => { if (!state.notice) return; const timer = setTimeout(() => platform.set({ notice: null }), 5000); return () => clearTimeout(timer); }, [state.notice]);
  const activeRequest = state.requests.find(r => r.expiresAt > Date.now());
  const incoming = state.transfers.find(t => t.receiverId === state.device?.id && t.status === 'waiting');
  return <div className="app-shell"><aside className="sidebar"><div className="sidebar-brand"><Brand/></div><div className="workspace-label">YOUR WORKSPACE</div><nav className="side-navigation" aria-label="Main navigation">{navigation.map(({ href, label, Icon }) => <Link key={href} href={href} aria-label={label} className={path.startsWith(href) ? 'active' : ''}><Icon size={19}/><span>{label}</span>{label === 'Devices' && state.devices.length > 0 && <span className="nav-count">{state.devices.length}</span>}</Link>)}</nav><div className="sidebar-device"><span className="eyebrow">THIS DEVICE</span><div className="sidebar-device-detail"><span className="mini-device"><DeviceIcon type={state.device?.type || 'laptop'} size={21}/></span><div><strong>{state.device?.name || 'This device'}</strong><span><i className={`status-dot ${state.status === 'online' ? '' : 'muted'}`}/>{state.status === 'online' ? 'Ready to connect' : connectionLabels[state.status]}</span></div></div></div><div className="sidebar-spacer"/><div className="privacy-note"><span className="privacy-icon"><ShieldCheck size={19}/></span><strong>Yours stays yours.</strong><p>Your files take the shortest path.<br/>Your privacy comes first.</p><Link href="/privacy">How transfers work <ArrowUpRight size={13}/></Link></div><nav className="side-navigation secondary" aria-label="Preferences"><Link href="/settings" className={path === '/settings' ? 'active' : ''}><Settings2 size={18}/> Settings</Link><button onClick={() => setHelp(true)}><CircleHelp size={18}/> Help & tips</button></nav><div className="guest-profile"><span className="profile-avatar">{state.device?.userId ? <Check size={19}/> : <Laptop size={19}/>}</span><div><strong>{state.device?.userId ? 'Your account' : 'Guest workspace'}</strong><span>{state.device?.userId ? 'Device linked' : 'No account needed'}</span></div><Link href={state.device?.userId ? '/settings' : '/auth/sign-in'} aria-label="Account settings"><ArrowUpRight size={16}/></Link></div></aside>
    <div className="workspace"><header className="app-header"><div className="mobile-brand"><Brand/></div><div className="header-breadcrumb">Workspace <span>/</span> <strong>{path.startsWith('/transfer/') ? 'Transfer details' : navigation.find(n => path.startsWith(n.href))?.label || (path === '/connect' ? 'Connect a device' : 'Settings')}</strong></div><div className="header-actions"><span className={`online-label ${state.status !== 'online' ? 'not-online' : ''}`}>{state.status === 'online' ? <><i className="status-dot"/> You’re online</> : <><WifiOff size={14}/>{connectionLabels[state.status]}</>}</span><span className="header-divider"/><ThemeButton/><button className="button primary small" aria-label="Connect device" onClick={() => setPair(true)} disabled={state.status !== 'online'}><Plus size={17}/><span>Connect device</span></button></div></header>
    {!['starting', 'online'].includes(state.status) && <div className="offline-banner" role="status"><WifiOff size={16}/><span>{connectionHints[state.status]}</span>{state.status === 'server-unavailable' && <button className="button secondary-button small" onClick={() => platform.reconnect()}>Try again</button>}</div>}
    {incoming && path !== '/drop' && path !== `/transfer/${incoming.id}` && <div className="incoming-banner" role="status"><ArrowUpRight size={17}/><span>{incoming.senderName} wants to send <strong>{incoming.item.name}</strong></span><Link className="button primary small" href={`/transfer/${incoming.id}`}>Review transfer</Link></div>}
    <main className="app-content" id="main-content">{children}</main><footer className="app-footer"><span><ShieldCheck size={14}/> Private by design. Simple by nature.</span><span>Open. Connect. Drop. Done.<i/> NearDrop v1.0</span></footer></div>
    <nav className="mobile-navigation" aria-label="Mobile navigation">{[...navigation, { href: '/settings', label: 'Settings', Icon: Settings2 }].map(({href,label,Icon}) => <Link href={href} key={href} className={path.startsWith(href) ? 'active' : ''}><Icon size={21}/><span>{label}</span></Link>)}</nav>
    {(state.error || state.notice) && <div className={`toast ${state.error ? 'error' : ''}`} role={state.error ? 'alert' : 'status'}>{state.error ? <CircleHelp size={19}/> : <Check size={19}/>}<span>{state.error || state.notice}</span><button className="icon-button" aria-label="Dismiss message" onClick={() => platform.clearMessages()}><X size={16}/></button></div>}
    {pair && <Modal title="Connect a device" onClose={() => setPair(false)}><p className="modal-description">A small connection. Endless possibilities.</p><PairingPanel onPaired={() => setPair(false)}/></Modal>}
    {activeRequest && <Modal title="A device wants to connect" onClose={() => { void platform.respondPair(activeRequest.id, false).catch(e => platform.error(e)); }}><div className="request-device"><span className="feature-icon"><DeviceIcon type={activeRequest.device.type} size={32}/></span><h3>{activeRequest.device.name}</h3><p>Only connect if you recognize this device and initiated pairing.</p></div><div className="modal-actions"><button className="button secondary-button" onClick={() => void platform.respondPair(activeRequest.id, false).catch(e => platform.error(e))}>Decline</button><button className="button primary" onClick={() => void platform.respondPair(activeRequest.id, true).catch(e => platform.error(e))}>Connect</button></div></Modal>}
    {help && <Modal title="Open. Connect. Drop. Done." onClose={() => setHelp(false)}><ol className="help-steps"><li><span>01</span><div><h3>Open NearDrop on both devices</h3><p>Use the same NearDrop address. Keep both screens awake during a transfer.</p></div></li><li><span>02</span><div><h3>Make the connection</h3><p>Scan the QR code or enter the pairing code. Confirm the device you recognize.</p></div></li><li><span>03</span><div><h3>Send something over</h3><p>Choose files, drop them here, or paste text. Accept on the receiving device, then save your file.</p></div></li></ol><Link href="/privacy" className="button secondary-button" onClick={() => setHelp(false)}>Privacy & browser support</Link></Modal>}
  </div>;
}
