'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowDownLeft, ArrowUpRight, Check, Copy, Download, File, FileImage, FileText, Film, Link2, RotateCcw, X } from 'lucide-react';
import { formatBytes, safeLink, terminalStates, type Transfer } from '@/shared/protocol';
import { usePlatform, useProgress } from '@/lib/hooks';
import { platform } from '@/lib/platform-client';
import { Modal, Spinner } from './primitives';
import { copyText } from '@/lib/clipboard';
export function FileIcon({ transfer }: { transfer: Transfer }) { const kind = transfer.item.kind; const mime = transfer.item.mime; const Icon = kind === 'link' ? Link2 : kind === 'text' ? FileText : mime.startsWith('image/') ? FileImage : mime.startsWith('video/') ? Film : File; return <Icon size={22} strokeWidth={1.6}/>; }
export function TransferCard({ transfer: t, compact = false }: { transfer: Transfer; compact?: boolean }) {
  const state = usePlatform(); const progress = useProgress(t.id); const [busy, setBusy] = useState(false); const [textOpen, setTextOpen] = useState(false);
  const sending = t.senderId === state.device?.id; const complete = t.status === 'completed'; const incoming = !sending && t.status === 'waiting'; const content = state.received[t.id];
  const percent = complete ? 100 : progress?.percent || 0;
  const status = { queued: 'Waiting in queue', waiting: sending ? `Waiting for ${t.receiverName}…` : 'Incoming transfer', preparing: 'Preparing transfer…', connecting: 'Connecting…', transferring: percent > 90 ? 'Almost there' : sending ? 'Sending' : 'Receiving', completed: sending ? 'Sent' : 'Received', cancelled: 'Cancelled', rejected: 'Declined', failed: 'Transfer interrupted' }[t.status];
  async function accept() { setBusy(true); try { await platform.accept(t); } catch (error) { platform.error(error); } finally { setBusy(false); } }
  const run = (action: 'reject' | 'cancel') => void platform.action(t.id, action).catch(e => platform.error(e));
  return <article className={`transfer-card ${incoming ? 'incoming' : ''} ${compact ? 'compact' : ''}`}><div className={`file-icon ${t.item.kind}`}><FileIcon transfer={t}/></div><div className="transfer-main"><div className="transfer-title"><Link href={`/transfer/${t.id}`}>{t.item.name}</Link><span className={`transfer-state ${complete ? 'success-text' : ''}`}>{complete && <Check size={13}/>} {status}</span></div><div className="transfer-meta"><span>{formatBytes(t.item.size)}</span><i/><span>{sending ? <ArrowUpRight size={12}/> : <ArrowDownLeft size={12}/>} {sending ? `To ${t.receiverName}` : `From ${t.senderName}`}</span><span className="transfer-time">{new Date(t.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div>
    {!terminalStates.includes(t.status) && !incoming && <div className="transfer-progress"><div className="progress-track" role="progressbar" aria-label={`Transfer progress for ${t.item.name}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(percent)}><div style={{ width: `${percent}%` }}/></div><div className="progress-caption"><span>{Math.round(percent)}%</span>{progress && progress.speed > 0 && <span>{formatBytes(progress.speed)}/s <i/> {progress.eta ? `${Math.ceil(progress.eta)} sec remaining` : 'Finishing…'}</span>}</div></div>}
    {incoming && <div className="incoming-actions"><span>{t.senderName} wants to send you {t.item.kind === 'file' ? 'a file' : t.item.kind === 'link' ? 'a link' : 'text'}.</span><div><button className="button small secondary-button" onClick={() => run('reject')} disabled={busy}>Decline</button><button className="button small primary" onClick={() => void accept()} disabled={busy}>{busy && <Spinner/>} Accept</button></div></div>}
    {complete && content && <div className="received-actions">{content.url && <a className="button small primary" href={content.url} download={t.item.name}><Download size={15}/> Save file</a>}{content.saved && <span className="success-text"><Check size={14}/> Written to your selected file</span>}{content.text !== undefined && <><button className="button small secondary-button" onClick={() => setTextOpen(true)}><FileText size={15}/> View {t.item.kind === 'link' ? 'link' : 'text'}</button><button className="button small secondary-button" onClick={() => void copyText(content.text!).then(() => platform.notify('Copied to clipboard')).catch(() => setTextOpen(true))}><Copy size={14}/> Copy</button></>}<button className="text-button muted-text" onClick={() => void platform.dismissReceived(t.id)}>Dismiss</button></div>}
    {t.status === 'failed' && <p className="failure-copy">Your connection was lost before the transfer finished. {sending && !platform.canRetry(t.id) ? 'Choose the file again to retry.' : ''}</p>}
  </div><div className="transfer-actions">{!terminalStates.includes(t.status) && !incoming && <button className="icon-button" aria-label={`Cancel ${t.item.name}`} onClick={() => run('cancel')}><X size={17}/></button>}{['failed', 'cancelled', 'rejected'].includes(t.status) && sending && platform.canRetry(t.id) && <button className="icon-button" aria-label={`Retry ${t.item.name}`} onClick={() => platform.retry(t.id)}><RotateCcw size={17}/></button>}</div>{textOpen && content?.text !== undefined && <Modal title={t.item.kind === 'link' ? 'Link received' : 'Text received'} onClose={() => setTextOpen(false)}><textarea className="received-text" readOnly value={content.text} aria-label="Received text" onFocus={e => e.target.select()}/><p className="muted-text">Select the text to copy it manually if clipboard access is unavailable.</p><div className="modal-actions"><button className="button secondary-button" onClick={() => void copyText(content.text!).then(() => platform.notify('Copied to clipboard')).catch(() => platform.error('Select the text and use your device’s Copy action.'))}>Copy</button>{t.item.kind === 'link' && safeLink(content.text) && <a className="button primary" href={safeLink(content.text)!} target="_blank" rel="noopener noreferrer">Open link <ArrowUpRight size={16}/></a>}</div></Modal>}</article>;
}
