'use client';
import { useEffect, useState } from 'react';
import { Modal } from '@/components/primitives';
import { chatApi } from './client-api';
import type { LinkedSession, Profile } from './shared';
export function NewConversation({ onClose,onCreated }: {onClose():void;onCreated(id:string):void}) {
 const [group,setGroup]=useState(false),[names,setNames]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <Modal title="Start a conversation" onClose={onClose}><form className="nc-form" onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void chatApi<{id:string}>('/rooms',{kind:group?'group':'direct',name,members:names.split(',').map(s=>s.trim()).filter(Boolean)}).then(r=>onCreated(r.id)).catch(cause=>setError(cause.message)).finally(()=>setBusy(false));}}><label className="nc-check"><input type="checkbox" checked={group} onChange={e=>setGroup(e.target.checked)}/> Create a group</label>{group&&<label>Group name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>}<label>{group?'Usernames, separated by commas':'Their username'}<input autoFocus required value={names} onChange={e=>setNames(e.target.value)} placeholder={group?'alex, sam, riley':'alex'} maxLength={750}/></label><p>Ask your friend for their exact NearChat username.</p>{error&&<p role="alert" className="nc-error">{error}</p>}<button className="nc-primary" disabled={busy}>{busy?'Creating…':'Start chat'}</button></form></Modal>;
}
export function ProfileDialog({profile,onClose,onSaved}:{profile:Profile;onClose():void;onSaved(profile:Profile):void}) {
 const [name,setName]=useState(profile.displayName),[username,setUsername]=useState(profile.username),[error,setError]=useState('');
 return <Modal title="Your NearChat profile" onClose={onClose}><form className="nc-form" onSubmit={e=>{e.preventDefault();void chatApi<{profile:Profile}>('/me',{displayName:name,username},'PATCH').then(r=>onSaved(r.profile)).catch(cause=>setError(cause.message));}}><label>Display name<input required value={name} maxLength={48} onChange={e=>setName(e.target.value)}/></label><label>Username<input required pattern="[a-z][a-z0-9_]{2,23}" minLength={3} maxLength={24} value={username} onChange={e=>setUsername(e.target.value.toLowerCase())}/></label><p>3–24 characters. Start with a letter; use letters, numbers and underscores. Share this username so friends can find you.</p>{error&&<p role="alert" className="nc-error">{error}</p>}<button className="nc-primary">Save profile</button></form></Modal>;
}
export function LinkDevice({initialCode='',onClose}:{initialCode?:string;onClose():void}) {
 const [code,setCode]=useState(initialCode),[name,setName]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false),[busy,setBusy]=useState(false);
 async function submit(approve:boolean){setBusy(true);setError('');try{const r=await chatApi<{name:string}>('/link/approve',{code,approve});setName(r.name);if(approve)setDone(true);}catch(cause){setError(cause instanceof Error?cause.message:'Could not link this device.');}finally{setBusy(false);}}
 return <Modal title="Link a device" onClose={onClose}>{done?<div className="nc-form"><h3>Device linked.</h3><p>Manage or revoke access from Linked devices.</p><button className="nc-primary" onClick={onClose}>Done</button></div>:<form className="nc-form" onSubmit={e=>{e.preventDefault();void submit(!!name);}}>{!name?<><label>Desktop pairing code<input autoFocus required value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={8} placeholder="ABC-234"/></label><p>Or scan the desktop QR with your phone camera and open its NearChat link.</p></>:<><h3>Sign in on {name}?</h3><p>This device will get access to your NearChat conversations. Approve only a screen you opened yourself.</p></>}{error&&<p role="alert" className="nc-error">{error}</p>}<button className="nc-primary" disabled={busy}>{busy?'Please wait…':name?'Approve sign-in':'Check device'}</button></form>}</Modal>;
}
export function DevicesDialog({onClose}:{onClose():void}) {
 const [sessions,setSessions]=useState<LinkedSession[]|null>(null),[error,setError]=useState('');
 // Load on first dialog render without a global account-token cache.
 useEffect(()=>{let cancelled=false;void chatApi<{sessions:LinkedSession[]}>('/sessions').then(r=>{if(!cancelled)setSessions(r.sessions);}).catch(cause=>{if(!cancelled)setError(cause.message);});return()=>{cancelled=true;};},[]);
 return <Modal title="Linked devices" onClose={onClose}><div className="nc-form">{sessions?.map(s=><div className="nc-session" key={s.id}><div><strong>{s.name}{s.current?' · This device':''}</strong><small>Linked {new Date(s.createdAt).toLocaleDateString()}</small></div>{!s.current&&<button className="nc-secondary" onClick={()=>void chatApi(`/sessions/${s.id}`,{},'DELETE').then(()=>setSessions(items=>items!.filter(x=>x.id!==s.id))).catch(cause=>setError(cause.message))}>Revoke</button>}</div>)}{!sessions&&<p>Loading linked devices…</p>}{error&&<p role="alert" className="nc-error">{error}</p>}<p>Revoking a device signs it out on its next request. Your current session expires after 30 days.</p></div></Modal>;
}
